export interface ConstellationStar {
  id: string;
  name: string;
  /** Local coordinates, 0–1, within this constellation's own shape box. */
  x: number;
  y: number;
  size: number;
}

export interface ConstellationDef {
  id: string;
  name: string;
  stars: ConstellationStar[];
  edges: [string, string][];
  fact: string;
}

export const constellations: ConstellationDef[] = [
  {
    id: "orion",
    name: "Orion",
    fact: "Orion's belt — Alnitak, Alnilam, and Mintaka — sits almost exactly on the celestial equator, which is why the constellation is visible from nearly everywhere on Earth.",
    stars: [
      { id: "betelgeuse", name: "Betelgeuse", x: 0.62, y: 0.1, size: 3.4 },
      { id: "bellatrix", name: "Bellatrix", x: 0.22, y: 0.14, size: 2.2 },
      { id: "alnitak", name: "Alnitak", x: 0.56, y: 0.42, size: 2.0 },
      { id: "alnilam", name: "Alnilam", x: 0.44, y: 0.46, size: 2.1 },
      { id: "mintaka", name: "Mintaka", x: 0.32, y: 0.5, size: 1.9 },
      { id: "saiph", name: "Saiph", x: 0.52, y: 0.9, size: 2.3 },
      { id: "rigel", name: "Rigel", x: 0.12, y: 0.94, size: 3.6 },
    ],
    edges: [
      ["betelgeuse", "alnitak"],
      ["bellatrix", "mintaka"],
      ["alnitak", "alnilam"],
      ["alnilam", "mintaka"],
      ["alnitak", "saiph"],
      ["mintaka", "rigel"],
    ],
  },
  {
    id: "ursa-major",
    name: "Ursa Major",
    fact: "Mizar, the bend in the Dipper's handle, has a fainter companion star, Alcor, visible to the naked eye — ancient armies reportedly used it as an eyesight test.",
    stars: [
      { id: "dubhe", name: "Dubhe", x: 0.08, y: 0.32, size: 2.6 },
      { id: "merak", name: "Merak", x: 0.12, y: 0.58, size: 2.1 },
      { id: "phecda", name: "Phecda", x: 0.34, y: 0.64, size: 2.0 },
      { id: "megrez", name: "Megrez", x: 0.38, y: 0.36, size: 1.6 },
      { id: "alioth", name: "Alioth", x: 0.58, y: 0.28, size: 2.3 },
      { id: "mizar", name: "Mizar", x: 0.78, y: 0.16, size: 2.1 },
      { id: "alkaid", name: "Alkaid", x: 0.96, y: 0.04, size: 2.2 },
    ],
    edges: [
      ["dubhe", "merak"],
      ["merak", "phecda"],
      ["phecda", "megrez"],
      ["megrez", "dubhe"],
      ["megrez", "alioth"],
      ["alioth", "mizar"],
      ["mizar", "alkaid"],
    ],
  },
  {
    id: "cassiopeia",
    name: "Cassiopeia",
    fact: "Cassiopeia sits in a rich part of the Milky Way, near the galactic plane — one reason it's dense with visible star clusters.",
    stars: [
      { id: "caph", name: "Caph", x: 0.05, y: 0.34, size: 2.1 },
      { id: "shedar", name: "Shedar", x: 0.3, y: 0.06, size: 2.3 },
      { id: "gamma-cas", name: "Tsih", x: 0.52, y: 0.32, size: 2.4 },
      { id: "ruchbah", name: "Ruchbah", x: 0.75, y: 0.02, size: 1.9 },
      { id: "segin", name: "Segin", x: 0.98, y: 0.34, size: 1.8 },
    ],
    edges: [
      ["caph", "shedar"],
      ["shedar", "gamma-cas"],
      ["gamma-cas", "ruchbah"],
      ["ruchbah", "segin"],
    ],
  },
  {
    id: "ursa-minor",
    name: "Ursa Minor",
    fact: "Polaris, at the tip of the Little Dipper's handle, sits almost exactly above Earth's rotational axis — every other star appears to circle around it.",
    stars: [
      { id: "polaris", name: "Polaris", x: 0.5, y: 0.02, size: 2.4 },
      { id: "yildun", name: "Yildun", x: 0.42, y: 0.28, size: 1.3 },
      { id: "epsilon-umi", name: "Epsilon UMi", x: 0.3, y: 0.46, size: 1.2 },
      { id: "zeta-umi", name: "Zeta UMi", x: 0.14, y: 0.5, size: 1.4 },
      { id: "kochab", name: "Kochab", x: 0.06, y: 0.78, size: 2.1 },
      { id: "pherkad", name: "Pherkad", x: 0.28, y: 0.88, size: 1.9 },
      { id: "eta-umi", name: "Eta UMi", x: 0.4, y: 0.62, size: 1.1 },
    ],
    edges: [
      ["polaris", "yildun"],
      ["yildun", "epsilon-umi"],
      ["epsilon-umi", "zeta-umi"],
      ["zeta-umi", "eta-umi"],
      ["eta-umi", "epsilon-umi"],
      ["zeta-umi", "kochab"],
      ["kochab", "pherkad"],
      ["pherkad", "eta-umi"],
    ],
  },
  {
    id: "leo",
    name: "Leo",
    fact: "The 'Sickle' — the backwards-question-mark shape at Leo's head — is one of the most recognizable star patterns for finding the constellation by eye.",
    stars: [
      { id: "regulus", name: "Regulus", x: 0.1, y: 0.9, size: 2.9 },
      { id: "eta-leo", name: "Eta Leonis", x: 0.14, y: 0.62, size: 1.3 },
      { id: "algieba", name: "Algieba", x: 0.24, y: 0.36, size: 2.0 },
      { id: "zosma", name: "Zosma", x: 0.5, y: 0.16, size: 1.7 },
      { id: "chertan", name: "Chertan", x: 0.56, y: 0.4, size: 1.4 },
      { id: "denebola", name: "Denebola", x: 0.92, y: 0.06, size: 1.9 },
      { id: "adhafera", name: "Adhafera", x: 0.18, y: 0.14, size: 1.1 },
    ],
    edges: [
      ["regulus", "eta-leo"],
      ["eta-leo", "algieba"],
      ["algieba", "adhafera"],
      ["algieba", "zosma"],
      ["zosma", "chertan"],
      ["chertan", "regulus"],
      ["zosma", "denebola"],
    ],
  },
  {
    id: "scorpius",
    name: "Scorpius",
    fact: "Antares, Scorpius's red heart, gets its name from a Greek phrase meaning 'rival of Mars' — the two share a similar reddish color in the sky.",
    stars: [
      { id: "beta-sco", name: "Graffias", x: 0.06, y: 0.04, size: 1.6 },
      { id: "delta-sco", name: "Dschubba", x: 0.18, y: 0.12, size: 1.7 },
      { id: "pi-sco", name: "Pi Scorpii", x: 0.1, y: 0.24, size: 1.2 },
      { id: "antares", name: "Antares", x: 0.32, y: 0.3, size: 3.0 },
      { id: "tau-sco", name: "Tau Scorpii", x: 0.42, y: 0.44, size: 1.4 },
      { id: "epsilon-sco", name: "Epsilon Scorpii", x: 0.5, y: 0.58, size: 1.5 },
      { id: "mu-sco", name: "Mu Scorpii", x: 0.6, y: 0.68, size: 1.2 },
      { id: "shaula", name: "Shaula", x: 0.78, y: 0.86, size: 2.0 },
      { id: "lesath", name: "Lesath", x: 0.88, y: 0.94, size: 1.5 },
    ],
    edges: [
      ["beta-sco", "delta-sco"],
      ["delta-sco", "pi-sco"],
      ["delta-sco", "antares"],
      ["antares", "tau-sco"],
      ["tau-sco", "epsilon-sco"],
      ["epsilon-sco", "mu-sco"],
      ["mu-sco", "shaula"],
      ["shaula", "lesath"],
    ],
  },
  {
    id: "cygnus",
    name: "Cygnus",
    fact: "Cygnus is also known as the Northern Cross — and it flies along the Milky Way, wings outstretched, tail marked by the bright star Deneb.",
    stars: [
      { id: "deneb", name: "Deneb", x: 0.5, y: 0.02, size: 2.6 },
      { id: "sadr", name: "Sadr", x: 0.5, y: 0.36, size: 1.8 },
      { id: "delta-cyg", name: "Delta Cygni", x: 0.18, y: 0.24, size: 1.4 },
      { id: "gienah", name: "Gienah", x: 0.82, y: 0.5, size: 1.5 },
      { id: "albireo", name: "Albireo", x: 0.5, y: 0.96, size: 1.7 },
    ],
    edges: [
      ["deneb", "sadr"],
      ["sadr", "delta-cyg"],
      ["sadr", "gienah"],
      ["sadr", "albireo"],
    ],
  },
  {
    id: "lyra",
    name: "Lyra",
    fact: "Vega, Lyra's brightest star, was the northern pole star roughly 12,000 years ago and will be again in about 13,000 more, as Earth's axis slowly wobbles.",
    stars: [
      { id: "vega", name: "Vega", x: 0.14, y: 0.04, size: 3.2 },
      { id: "epsilon-lyr", name: "Epsilon Lyrae", x: 0.06, y: 0.22, size: 1.1 },
      { id: "zeta-lyr", name: "Zeta Lyrae", x: 0.4, y: 0.28, size: 1.3 },
      { id: "sheliak", name: "Sheliak", x: 0.6, y: 0.72, size: 1.5 },
      { id: "sulafat", name: "Sulafat", x: 0.9, y: 0.62, size: 1.6 },
    ],
    edges: [
      ["vega", "epsilon-lyr"],
      ["vega", "zeta-lyr"],
      ["zeta-lyr", "sheliak"],
      ["sheliak", "sulafat"],
      ["sulafat", "zeta-lyr"],
    ],
  },
  {
    id: "taurus",
    name: "Taurus",
    fact: "The V-shaped face of Taurus is the Hyades cluster — one of the nearest star clusters to Earth, with Aldebaran shining in front of it, unrelated but perfectly aligned.",
    stars: [
      { id: "aldebaran", name: "Aldebaran", x: 0.42, y: 0.5, size: 2.9 },
      { id: "hyad-1", name: "", x: 0.2, y: 0.42, size: 1.2 },
      { id: "hyad-2", name: "", x: 0.06, y: 0.3, size: 1.3 },
      { id: "elnath", name: "Elnath", x: 0.02, y: 0.02, size: 2.0 },
      { id: "zeta-tau", name: "Zeta Tauri", x: 0.3, y: 0.06, size: 1.4 },
      { id: "gamma-tau", name: "Gamma Tauri", x: 0.6, y: 0.62, size: 1.3 },
    ],
    edges: [
      ["elnath", "hyad-1"],
      ["hyad-1", "aldebaran"],
      ["aldebaran", "hyad-2"],
      ["aldebaran", "zeta-tau"],
      ["aldebaran", "gamma-tau"],
    ],
  },
  {
    id: "gemini",
    name: "Gemini",
    fact: "Castor and Pollux, the twin heads of Gemini, aren't true twins at all — Castor is a system of six stars, while Pollux is a single orange giant with its own known planet.",
    stars: [
      { id: "castor", name: "Castor", x: 0.1, y: 0.02, size: 2.2 },
      { id: "pollux", name: "Pollux", x: 0.3, y: 0.02, size: 2.5 },
      { id: "alhena", name: "Alhena", x: 0.6, y: 0.7, size: 1.8 },
      { id: "wasat", name: "Wasat", x: 0.24, y: 0.44, size: 1.3 },
      { id: "mebsuta", name: "Mebsuta", x: 0.08, y: 0.5, size: 1.4 },
      { id: "tejat", name: "Tejat", x: 0.9, y: 0.94, size: 1.5 },
    ],
    edges: [
      ["castor", "mebsuta"],
      ["pollux", "wasat"],
      ["wasat", "mebsuta"],
      ["wasat", "alhena"],
      ["alhena", "tejat"],
    ],
  },
  {
    id: "canis-major",
    name: "Canis Major",
    fact: "Sirius, the Dog Star, is the brightest star in Earth's night sky — not because it's unusually powerful, but because at 8.6 light-years, it's one of our nearest stellar neighbors.",
    stars: [
      { id: "sirius", name: "Sirius", x: 0.3, y: 0.02, size: 3.8 },
      { id: "mirzam", name: "Mirzam", x: 0.02, y: 0.14, size: 1.6 },
      { id: "wezen", name: "Wezen", x: 0.62, y: 0.5, size: 2.0 },
      { id: "adhara", name: "Adhara", x: 0.5, y: 0.74, size: 2.1 },
      { id: "aludra", name: "Aludra", x: 0.86, y: 0.7, size: 1.6 },
    ],
    edges: [
      ["mirzam", "sirius"],
      ["sirius", "wezen"],
      ["wezen", "adhara"],
      ["wezen", "aludra"],
    ],
  },
  {
    id: "aquila",
    name: "Aquila",
    fact: "Altair, at Aquila's heart, spins so fast — once every 9 hours — that it bulges outward at its equator instead of staying round.",
    stars: [
      { id: "altair", name: "Altair", x: 0.5, y: 0.4, size: 2.8 },
      { id: "tarazed", name: "Tarazed", x: 0.34, y: 0.16, size: 1.7 },
      { id: "alshain", name: "Alshain", x: 0.68, y: 0.56, size: 1.4 },
      { id: "delta-aql", name: "Delta Aquilae", x: 0.28, y: 0.7, size: 1.3 },
      { id: "lambda-aql", name: "Lambda Aquilae", x: 0.06, y: 0.92, size: 1.4 },
    ],
    edges: [
      ["tarazed", "altair"],
      ["altair", "alshain"],
      ["altair", "delta-aql"],
      ["delta-aql", "lambda-aql"],
    ],
  },
  {
    id: "sagittarius",
    name: "Sagittarius",
    fact: "Sagittarius's 'Teapot' asterism points its spout toward the center of the Milky Way — the galaxy's core lies just beyond it, hidden behind dust.",
    stars: [
      { id: "kaus-media", name: "Kaus Media", x: 0.12, y: 0.46, size: 1.8 },
      { id: "kaus-australis", name: "Kaus Australis", x: 0.06, y: 0.66, size: 2.1 },
      { id: "kaus-borealis", name: "Kaus Borealis", x: 0.22, y: 0.28, size: 1.6 },
      { id: "alnasl", name: "Alnasl", x: 0.02, y: 0.3, size: 1.3 },
      { id: "nunki", name: "Nunki", x: 0.5, y: 0.44, size: 2.0 },
      { id: "tau-sgr", name: "Tau Sagittarii", x: 0.7, y: 0.52, size: 1.3 },
      { id: "phi-sgr", name: "Phi Sagittarii", x: 0.4, y: 0.2, size: 1.3 },
      { id: "sigma-sgr", name: "Nunki-adjacent", x: 0.6, y: 0.16, size: 1.4 },
    ],
    edges: [
      ["alnasl", "kaus-media"],
      ["kaus-media", "kaus-australis"],
      ["kaus-media", "kaus-borealis"],
      ["kaus-borealis", "phi-sgr"],
      ["phi-sgr", "sigma-sgr"],
      ["kaus-media", "nunki"],
      ["nunki", "tau-sgr"],
      ["nunki", "sigma-sgr"],
    ],
  },
  {
    id: "pegasus",
    name: "Pegasus",
    fact: "The Great Square of Pegasus is so large and empty of bright stars that astronomers use it as a 'star-poor' benchmark for testing how dark a sky truly is.",
    stars: [
      { id: "markab", name: "Markab", x: 0.06, y: 0.86, size: 2.0 },
      { id: "scheat", name: "Scheat", x: 0.1, y: 0.1, size: 1.9 },
      { id: "algenib", name: "Algenib", x: 0.9, y: 0.9, size: 1.7 },
      { id: "alpheratz", name: "Alpheratz", x: 0.94, y: 0.14, size: 2.1 },
      { id: "enif", name: "Enif", x: 0.0, y: 0.6, size: 1.8 },
    ],
    edges: [
      ["markab", "scheat"],
      ["scheat", "alpheratz"],
      ["alpheratz", "algenib"],
      ["algenib", "markab"],
      ["markab", "enif"],
    ],
  },
  {
    id: "corona-borealis",
    name: "Corona Borealis",
    fact: "In Greek myth, the Northern Crown was the jeweled diadem of Ariadne, tossed into the sky by Dionysus and set alight among the stars.",
    stars: [
      { id: "alphecca", name: "Alphecca", x: 0.5, y: 0.02, size: 2.1 },
      { id: "nusakan", name: "Nusakan", x: 0.14, y: 0.2, size: 1.3 },
      { id: "theta-crb", name: "Theta CrB", x: 0.02, y: 0.5, size: 1.0 },
      { id: "gamma-crb", name: "Gamma CrB", x: 0.78, y: 0.18, size: 1.2 },
      { id: "delta-crb", name: "Delta CrB", x: 0.96, y: 0.46, size: 1.1 },
      { id: "epsilon-crb", name: "Epsilon CrB", x: 0.86, y: 0.68, size: 1.0 },
    ],
    edges: [
      ["theta-crb", "nusakan"],
      ["nusakan", "alphecca"],
      ["alphecca", "gamma-crb"],
      ["gamma-crb", "delta-crb"],
      ["delta-crb", "epsilon-crb"],
    ],
  },
  {
    id: "andromeda",
    name: "Andromeda",
    fact: "The Andromeda Galaxy, our nearest large galactic neighbor, is visible to the naked eye from this constellation as a faint smudge — over 2.5 million light-years away.",
    stars: [
      { id: "alpheratz-and", name: "Alpheratz", x: 0.04, y: 0.06, size: 2.1 },
      { id: "delta-and", name: "Delta Andromedae", x: 0.26, y: 0.22, size: 1.4 },
      { id: "mirach", name: "Mirach", x: 0.5, y: 0.38, size: 2.0 },
      { id: "mu-and", name: "Mu Andromedae", x: 0.66, y: 0.5, size: 1.2 },
      { id: "almach", name: "Almach", x: 0.94, y: 0.7, size: 1.8 },
    ],
    edges: [
      ["alpheratz-and", "delta-and"],
      ["delta-and", "mirach"],
      ["mirach", "mu-and"],
      ["mu-and", "almach"],
    ],
  },
  {
    id: "perseus",
    name: "Perseus",
    fact: "Algol, Perseus's second brightest star, is a true 'demon star' — an eclipsing binary that visibly dims every few days as one star passes in front of the other.",
    stars: [
      { id: "mirfak", name: "Mirfak", x: 0.4, y: 0.1, size: 2.3 },
      { id: "algol", name: "Algol", x: 0.14, y: 0.34, size: 2.0 },
      { id: "delta-per", name: "Delta Persei", x: 0.6, y: 0.32, size: 1.4 },
      { id: "epsilon-per", name: "Epsilon Persei", x: 0.82, y: 0.5, size: 1.5 },
      { id: "zeta-per", name: "Zeta Persei", x: 0.7, y: 0.68, size: 1.4 },
      { id: "gamma-per", name: "Gamma Persei", x: 0.32, y: 0.4, size: 1.2 },
    ],
    edges: [
      ["algol", "gamma-per"],
      ["gamma-per", "mirfak"],
      ["mirfak", "delta-per"],
      ["delta-per", "epsilon-per"],
      ["epsilon-per", "zeta-per"],
    ],
  },
  {
    id: "auriga",
    name: "Auriga",
    fact: "Capella, Auriga's brightest star, is actually a close pair of giant yellow stars orbiting each other, appearing as one bright point to the naked eye.",
    stars: [
      { id: "capella", name: "Capella", x: 0.16, y: 0.06, size: 2.9 },
      { id: "menkalinan", name: "Menkalinan", x: 0.62, y: 0.02, size: 1.7 },
      { id: "theta-aur", name: "Theta Aurigae", x: 0.86, y: 0.44, size: 1.4 },
      { id: "elnath-aur", name: "Elnath", x: 0.5, y: 0.68, size: 1.5 },
      { id: "hassaleh", name: "Hassaleh", x: 0.06, y: 0.4, size: 1.3 },
    ],
    edges: [
      ["capella", "hassaleh"],
      ["capella", "menkalinan"],
      ["menkalinan", "theta-aur"],
      ["theta-aur", "elnath-aur"],
      ["elnath-aur", "hassaleh"],
    ],
  },
  {
    id: "bootes",
    name: "Boötes",
    fact: "Arcturus, Boötes' brightest star, is one of the fastest-moving stars visible to the naked eye — it's just passing through our galactic neighborhood.",
    stars: [
      { id: "arcturus", name: "Arcturus", x: 0.42, y: 0.94, size: 3.1 },
      { id: "izar", name: "Izar", x: 0.58, y: 0.56, size: 1.5 },
      { id: "seginus", name: "Seginus", x: 0.44, y: 0.28, size: 1.4 },
      { id: "nekkar", name: "Nekkar", x: 0.2, y: 0.14, size: 1.2 },
      { id: "muphrid", name: "Muphrid", x: 0.18, y: 0.7, size: 1.4 },
    ],
    edges: [
      ["arcturus", "muphrid"],
      ["arcturus", "izar"],
      ["izar", "seginus"],
      ["seginus", "nekkar"],
    ],
  },
  {
    id: "virgo",
    name: "Virgo",
    fact: "Spica, Virgo's brightest star, is actually two massive stars so close together they distort each other into egg shapes — too close to ever see as separate points.",
    stars: [
      { id: "spica", name: "Spica", x: 0.5, y: 0.92, size: 2.7 },
      { id: "porrima", name: "Porrima", x: 0.34, y: 0.5, size: 1.5 },
      { id: "vindemiatrix", name: "Vindemiatrix", x: 0.7, y: 0.2, size: 1.4 },
      { id: "heze", name: "Heze", x: 0.5, y: 0.62, size: 1.2 },
      { id: "zaniah", name: "Zaniah", x: 0.14, y: 0.32, size: 1.1 },
    ],
    edges: [
      ["zaniah", "porrima"],
      ["porrima", "heze"],
      ["heze", "spica"],
      ["porrima", "vindemiatrix"],
    ],
  },
  {
    id: "aquarius",
    name: "Aquarius",
    fact: "Aquarius lies in a stretch of sky ancient astronomers called the 'Sea' — a whole neighborhood of water-associated constellations, from Pisces to Cetus.",
    stars: [
      { id: "sadalsuud", name: "Sadalsuud", x: 0.2, y: 0.12, size: 1.9 },
      { id: "sadalmelik", name: "Sadalmelik", x: 0.42, y: 0.28, size: 1.8 },
      { id: "sadachbia", name: "Sadachbia", x: 0.64, y: 0.46, size: 1.3 },
      { id: "skat", name: "Skat", x: 0.86, y: 0.7, size: 1.5 },
      { id: "albali", name: "Albali", x: 0.06, y: 0.36, size: 1.2 },
    ],
    edges: [
      ["albali", "sadalsuud"],
      ["sadalsuud", "sadalmelik"],
      ["sadalmelik", "sadachbia"],
      ["sadachbia", "skat"],
    ],
  },
  {
    id: "pisces",
    name: "Pisces",
    fact: "Pisces is faint and famously hard to pick out — its two fish are tied together by a long, dim cord of stars meeting at the knot star, Alrescha.",
    stars: [
      { id: "alrescha", name: "Alrescha", x: 0.5, y: 0.8, size: 1.6 },
      { id: "eta-psc", name: "Eta Piscium", x: 0.28, y: 0.5, size: 1.5 },
      { id: "omega-psc", name: "Omega Piscium", x: 0.14, y: 0.18, size: 1.1 },
      { id: "gamma-psc", name: "Gamma Piscium", x: 0.76, y: 0.36, size: 1.2 },
      { id: "iota-psc", name: "Iota Piscium", x: 0.92, y: 0.08, size: 1.1 },
    ],
    edges: [
      ["omega-psc", "eta-psc"],
      ["eta-psc", "alrescha"],
      ["alrescha", "gamma-psc"],
      ["gamma-psc", "iota-psc"],
    ],
  },
  {
    id: "aries",
    name: "Aries",
    fact: "Aries used to mark the Sun's position at the spring equinox, giving its name to the 'First Point of Aries' — though precession has since shifted that point into Pisces.",
    stars: [
      { id: "hamal", name: "Hamal", x: 0.7, y: 0.2, size: 2.1 },
      { id: "sheratan", name: "Sheratan", x: 0.3, y: 0.5, size: 1.6 },
      { id: "mesarthim", name: "Mesarthim", x: 0.1, y: 0.66, size: 1.3 },
    ],
    edges: [
      ["mesarthim", "sheratan"],
      ["sheratan", "hamal"],
    ],
  },
  {
    id: "cancer",
    name: "Cancer",
    fact: "Cancer is the faintest of the zodiac constellations — but it hides the Beehive Cluster, a swarm of hundreds of stars visible as a soft glow to the naked eye.",
    stars: [
      { id: "acubens", name: "Acubens", x: 0.78, y: 0.86, size: 1.5 },
      { id: "al-tarf", name: "Al Tarf", x: 0.94, y: 0.5, size: 1.3 },
      { id: "asellus-borealis", name: "Asellus Borealis", x: 0.4, y: 0.3, size: 1.2 },
      { id: "asellus-australis", name: "Asellus Australis", x: 0.44, y: 0.5, size: 1.3 },
      { id: "iota-cnc", name: "Iota Cancri", x: 0.1, y: 0.06, size: 1.1 },
    ],
    edges: [
      ["iota-cnc", "asellus-borealis"],
      ["asellus-borealis", "asellus-australis"],
      ["asellus-australis", "al-tarf"],
      ["asellus-australis", "acubens"],
    ],
  },
  {
    id: "capricornus",
    name: "Capricornus",
    fact: "Capricornus is shaped like a triangle with a long tail — ancient cultures across Babylon and Greece both saw it as a goat with a fish's tail.",
    stars: [
      { id: "algedi", name: "Algedi", x: 0.04, y: 0.3, size: 1.5 },
      { id: "dabih", name: "Dabih", x: 0.14, y: 0.44, size: 1.6 },
      { id: "nashira", name: "Nashira", x: 0.84, y: 0.62, size: 1.4 },
      { id: "deneb-algedi", name: "Deneb Algedi", x: 0.96, y: 0.68, size: 1.5 },
      { id: "omega-cap", name: "Omega Capricorni", x: 0.5, y: 0.9, size: 1.2 },
    ],
    edges: [
      ["algedi", "dabih"],
      ["dabih", "omega-cap"],
      ["omega-cap", "nashira"],
      ["nashira", "deneb-algedi"],
    ],
  },
  {
    id: "libra",
    name: "Libra",
    fact: "Libra is the only zodiac constellation representing an object rather than a creature — its brightest stars were once considered the claws of neighboring Scorpius.",
    stars: [
      { id: "zubenelgenubi", name: "Zubenelgenubi", x: 0.14, y: 0.7, size: 1.9 },
      { id: "zubeneschamali", name: "Zubeneschamali", x: 0.5, y: 0.2, size: 1.8 },
      { id: "zubenelakrab", name: "Zubenelakrab", x: 0.8, y: 0.5, size: 1.3 },
      { id: "sigma-lib", name: "Sigma Librae", x: 0.9, y: 0.86, size: 1.4 },
    ],
    edges: [
      ["zubenelgenubi", "zubeneschamali"],
      ["zubeneschamali", "zubenelakrab"],
      ["zubenelakrab", "sigma-lib"],
    ],
  },
  {
    id: "hercules",
    name: "Hercules",
    fact: "The 'Keystone' — the trapezoid at Hercules's center — points the way to M13, one of the brightest globular star clusters visible from the northern sky.",
    stars: [
      { id: "kornephoros", name: "Kornephoros", x: 0.1, y: 0.5, size: 1.8 },
      { id: "pi-her", name: "Pi Herculis", x: 0.34, y: 0.28, size: 1.3 },
      { id: "eta-her", name: "Eta Herculis", x: 0.6, y: 0.32, size: 1.2 },
      { id: "zeta-her", name: "Zeta Herculis", x: 0.5, y: 0.58, size: 1.4 },
      { id: "epsilon-her", name: "Epsilon Herculis", x: 0.82, y: 0.14, size: 1.2 },
      { id: "sarin", name: "Sarin", x: 0.9, y: 0.66, size: 1.5 },
    ],
    edges: [
      ["kornephoros", "zeta-her"],
      ["zeta-her", "pi-her"],
      ["pi-her", "eta-her"],
      ["eta-her", "epsilon-her"],
      ["zeta-her", "sarin"],
    ],
  },
  {
    id: "cepheus",
    name: "Cepheus",
    fact: "Delta Cephei, in this constellation, gave its name to an entire class of pulsating stars — Cepheid variables — that astronomers use to measure distances across the universe.",
    stars: [
      { id: "alderamin", name: "Alderamin", x: 0.14, y: 0.7, size: 1.9 },
      { id: "alfirk", name: "Alfirk", x: 0.06, y: 0.36, size: 1.5 },
      { id: "errai", name: "Errai", x: 0.4, y: 0.06, size: 1.6 },
      { id: "delta-cep", name: "Delta Cephei", x: 0.7, y: 0.5, size: 1.2 },
      { id: "zeta-cep", name: "Zeta Cephei", x: 0.86, y: 0.78, size: 1.3 },
    ],
    edges: [
      ["alfirk", "alderamin"],
      ["alfirk", "errai"],
      ["errai", "delta-cep"],
      ["delta-cep", "zeta-cep"],
      ["delta-cep", "alderamin"],
    ],
  },
  {
    id: "canis-minor",
    name: "Canis Minor",
    fact: "Canis Minor has just two bright stars — but one of them, Procyon, is among the closest stars to Earth, at just over 11 light-years away.",
    stars: [
      { id: "procyon", name: "Procyon", x: 0.2, y: 0.7, size: 2.6 },
      { id: "gomeisa", name: "Gomeisa", x: 0.8, y: 0.1, size: 1.5 },
    ],
    edges: [["gomeisa", "procyon"]],
  },
  {
    id: "crux",
    name: "Crux",
    fact: "The Southern Cross is the smallest of all 88 constellations — but its long axis points almost directly toward the south celestial pole, making it a reliable compass.",
    stars: [
      { id: "acrux", name: "Acrux", x: 0.5, y: 0.94, size: 2.6 },
      { id: "mimosa", name: "Mimosa", x: 0.1, y: 0.42, size: 2.3 },
      { id: "gacrux", name: "Gacrux", x: 0.5, y: 0.04, size: 2.1 },
      { id: "delta-cru", name: "Delta Crucis", x: 0.86, y: 0.5, size: 1.6 },
    ],
    edges: [
      ["gacrux", "acrux"],
      ["mimosa", "delta-cru"],
    ],
  },
  {
    id: "ophiuchus",
    name: "Ophiuchus",
    fact: "Ophiuchus, the 'Serpent Bearer', straddles the ecliptic between Scorpius and Sagittarius — some call it the thirteenth zodiac sign, though it was never traditionally counted.",
    stars: [
      { id: "rasalhague", name: "Rasalhague", x: 0.46, y: 0.02, size: 2.1 },
      { id: "cebalrai", name: "Cebalrai", x: 0.66, y: 0.18, size: 1.4 },
      { id: "sabik", name: "Sabik", x: 0.56, y: 0.6, size: 1.7 },
      { id: "yed-prior", name: "Yed Prior", x: 0.16, y: 0.24, size: 1.5 },
      { id: "yed-posterior", name: "Yed Posterior", x: 0.24, y: 0.26, size: 1.3 },
      { id: "theta-oph", name: "Theta Ophiuchi", x: 0.4, y: 0.9, size: 1.4 },
    ],
    edges: [
      ["yed-prior", "yed-posterior"],
      ["yed-posterior", "rasalhague"],
      ["rasalhague", "cebalrai"],
      ["rasalhague", "sabik"],
      ["sabik", "theta-oph"],
    ],
  },
  {
    id: "draco",
    name: "Draco",
    fact: "Draco winds so far across the northern sky that its tail sits between the two Dippers — around 4,700 years ago, its star Thuban was the pole star, not Polaris.",
    stars: [
      { id: "thuban", name: "Thuban", x: 0.5, y: 0.9, size: 1.4 },
      { id: "eltanin", name: "Eltanin", x: 0.06, y: 0.06, size: 2.0 },
      { id: "rastaban", name: "Rastaban", x: 0.18, y: 0.1, size: 1.6 },
      { id: "altais", name: "Altais", x: 0.32, y: 0.2, size: 1.4 },
      { id: "grumium", name: "Grumium", x: 0.0, y: 0.14, size: 1.2 },
      { id: "edasich", name: "Edasich", x: 0.7, y: 0.5, size: 1.3 },
      { id: "chi-dra", name: "Chi Draconis", x: 0.86, y: 0.68, size: 1.2 },
    ],
    edges: [
      ["grumium", "eltanin"],
      ["eltanin", "rastaban"],
      ["rastaban", "altais"],
      ["altais", "edasich"],
      ["edasich", "chi-dra"],
      ["chi-dra", "thuban"],
    ],
  },
  {
    id: "camelopardalis",
    name: "Camelopardalis",
    fact: "Camelopardalis has no star brighter than 4th magnitude — it was invented in the 1600s to fill an oddly empty stretch of northern sky, and it still looks nearly empty.",
    stars: [
      { id: "beta-cam", name: "Beta Camelopardalis", x: 0.5, y: 0.1, size: 1.5 },
      { id: "alpha-cam", name: "Alpha Camelopardalis", x: 0.72, y: 0.4, size: 1.4 },
      { id: "cs-cam", name: "CS Camelopardalis", x: 0.3, y: 0.5, size: 1.1 },
      { id: "gamma-cam", name: "Gamma Camelopardalis", x: 0.1, y: 0.8, size: 1.2 },
    ],
    edges: [
      ["gamma-cam", "cs-cam"],
      ["cs-cam", "beta-cam"],
      ["beta-cam", "alpha-cam"],
    ],
  },
  {
    id: "lynx",
    name: "Lynx",
    fact: "Lynx was named for how faint it is — its 17th-century namer reportedly said you'd need the eyes of a lynx to see it at all.",
    stars: [
      { id: "alpha-lyn", name: "Alpha Lyncis", x: 0.5, y: 0.9, size: 1.6 },
      { id: "38-lyn", name: "38 Lyncis", x: 0.3, y: 0.5, size: 1.2 },
      { id: "31-lyn", name: "31 Lyncis", x: 0.14, y: 0.2, size: 1.3 },
      { id: "10-uma", name: "10 Ursae Majoris", x: 0.66, y: 0.06, size: 1.1 },
    ],
    edges: [
      ["10-uma", "31-lyn"],
      ["31-lyn", "38-lyn"],
      ["38-lyn", "alpha-lyn"],
    ],
  },
  {
    id: "sextans",
    name: "Sextans",
    fact: "Sextans commemorates the astronomical sextant — a naked-eye sighting instrument — that its namer used for decades of star measurements before telescopes took over the job.",
    stars: [
      { id: "alpha-sex", name: "Alpha Sextantis", x: 0.5, y: 0.5, size: 1.4 },
      { id: "beta-sex", name: "Beta Sextantis", x: 0.18, y: 0.3, size: 1.0 },
      { id: "gamma-sex", name: "Gamma Sextantis", x: 0.8, y: 0.7, size: 1.0 },
    ],
    edges: [
      ["beta-sex", "alpha-sex"],
      ["alpha-sex", "gamma-sex"],
    ],
  },
  {
    id: "corvus",
    name: "Corvus",
    fact: "Corvus's four brightest stars form a tidy, almost perfect quadrilateral — one of the most compact and recognizable shapes anywhere in the sky.",
    stars: [
      { id: "alchiba", name: "Alchiba", x: 0.1, y: 0.86, size: 1.3 },
      { id: "kraz", name: "Kraz", x: 0.36, y: 0.94, size: 1.4 },
      { id: "gienah-crv", name: "Gienah", x: 0.2, y: 0.16, size: 1.5 },
      { id: "algorab", name: "Algorab", x: 0.7, y: 0.1, size: 1.5 },
      { id: "minkar", name: "Minkar", x: 0.62, y: 0.5, size: 1.3 },
    ],
    edges: [
      ["alchiba", "gienah-crv"],
      ["gienah-crv", "algorab"],
      ["algorab", "minkar"],
      ["minkar", "kraz"],
      ["kraz", "alchiba"],
    ],
  },
  {
    id: "crater",
    name: "Crater",
    fact: "Crater represents the cup of Apollo — a faint, curved arc of stars just west of Corvus, holding almost no stars brighter than 4th magnitude.",
    stars: [
      { id: "alkes", name: "Alkes", x: 0.5, y: 0.9, size: 1.4 },
      { id: "beta-crt", name: "Beta Crateris", x: 0.2, y: 0.6, size: 1.1 },
      { id: "gamma-crt", name: "Gamma Crateris", x: 0.3, y: 0.3, size: 1.2 },
      { id: "delta-crt", name: "Delta Crateris", x: 0.62, y: 0.2, size: 1.3 },
      { id: "zeta-crt", name: "Zeta Crateris", x: 0.82, y: 0.44, size: 1.0 },
    ],
    edges: [
      ["beta-crt", "alkes"],
      ["beta-crt", "gamma-crt"],
      ["gamma-crt", "delta-crt"],
      ["delta-crt", "zeta-crt"],
    ],
  },
  {
    id: "hydra",
    name: "Hydra",
    fact: "Hydra is the largest of all 88 constellations, stretching a quarter of the way around the sky — but it has only one genuinely bright star, Alphard.",
    stars: [
      { id: "alphard", name: "Alphard", x: 0.3, y: 0.5, size: 2.2 },
      { id: "zeta-hya", name: "Zeta Hydrae", x: 0.52, y: 0.18, size: 1.3 },
      { id: "epsilon-hya", name: "Epsilon Hydrae", x: 0.66, y: 0.06, size: 1.2 },
      { id: "pi-hya", name: "Pi Hydrae", x: 0.14, y: 0.86, size: 1.3 },
      { id: "gamma-hya", name: "Gamma Hydrae", x: 0.9, y: 0.66, size: 1.4 },
      { id: "mu-hya", name: "Mu Hydrae", x: 0.06, y: 0.62, size: 1.1 },
    ],
    edges: [
      ["epsilon-hya", "zeta-hya"],
      ["zeta-hya", "alphard"],
      ["alphard", "mu-hya"],
      ["mu-hya", "pi-hya"],
      ["alphard", "gamma-hya"],
    ],
  },
  {
    id: "monoceros",
    name: "Monoceros",
    fact: "Monoceros, the Unicorn, is faint on its own but sits inside a rich patch of the winter Milky Way — flanked by Orion, Canis Major, and Canis Minor.",
    stars: [
      { id: "alpha-mon", name: "Alpha Monocerotis", x: 0.5, y: 0.86, size: 1.4 },
      { id: "beta-mon", name: "Beta Monocerotis", x: 0.3, y: 0.4, size: 1.5 },
      { id: "gamma-mon", name: "Gamma Monocerotis", x: 0.14, y: 0.1, size: 1.3 },
      { id: "delta-mon", name: "Delta Monocerotis", x: 0.7, y: 0.18, size: 1.1 },
    ],
    edges: [
      ["gamma-mon", "beta-mon"],
      ["beta-mon", "alpha-mon"],
      ["beta-mon", "delta-mon"],
    ],
  },
  {
    id: "lepus",
    name: "Lepus",
    fact: "Lepus, the Hare, crouches at Orion's feet — as if forever fleeing the hunter and his two dogs across the winter sky.",
    stars: [
      { id: "arneb", name: "Arneb", x: 0.5, y: 0.14, size: 2.0 },
      { id: "nihal", name: "Nihal", x: 0.4, y: 0.36, size: 1.5 },
      { id: "gamma-lep", name: "Gamma Leporis", x: 0.68, y: 0.5, size: 1.3 },
      { id: "delta-lep", name: "Delta Leporis", x: 0.8, y: 0.68, size: 1.2 },
      { id: "epsilon-lep", name: "Epsilon Leporis", x: 0.2, y: 0.5, size: 1.2 },
    ],
    edges: [
      ["arneb", "nihal"],
      ["nihal", "epsilon-lep"],
      ["nihal", "gamma-lep"],
      ["gamma-lep", "delta-lep"],
    ],
  },
  {
    id: "columba",
    name: "Columba",
    fact: "Columba, the Dove, is a relatively modern constellation, carved out from Canis Major's stars in the late 1500s to represent the dove from the story of Noah's Ark.",
    stars: [
      { id: "phact", name: "Phact", x: 0.4, y: 0.5, size: 1.8 },
      { id: "wazn", name: "Wazn", x: 0.66, y: 0.36, size: 1.4 },
      { id: "eta-col", name: "Eta Columbae", x: 0.2, y: 0.7, size: 1.2 },
      { id: "delta-col", name: "Delta Columbae", x: 0.86, y: 0.14, size: 1.2 },
    ],
    edges: [
      ["eta-col", "phact"],
      ["phact", "wazn"],
      ["wazn", "delta-col"],
    ],
  },
  {
    id: "delphinus",
    name: "Delphinus",
    fact: "Delphinus is tiny but distinct — a neat diamond of stars nicknamed 'Job's Coffin', leaping through a quiet stretch of the summer sky.",
    stars: [
      { id: "sualocin", name: "Sualocin", x: 0.7, y: 0.3, size: 1.5 },
      { id: "rotanev", name: "Rotanev", x: 0.5, y: 0.2, size: 1.4 },
      { id: "gamma-del", name: "Gamma Delphini", x: 0.16, y: 0.4, size: 1.3 },
      { id: "delta-del", name: "Delta Delphini", x: 0.4, y: 0.5, size: 1.1 },
      { id: "epsilon-del", name: "Epsilon Delphini", x: 0.72, y: 0.8, size: 1.2 },
    ],
    edges: [
      ["gamma-del", "delta-del"],
      ["delta-del", "rotanev"],
      ["rotanev", "sualocin"],
      ["delta-del", "epsilon-del"],
    ],
  },
  {
    id: "sagitta",
    name: "Sagitta",
    fact: "Sagitta, the Arrow, is the third-smallest constellation in the sky — a thin, unmistakable sliver aimed across the Milky Way toward Aquila.",
    stars: [
      { id: "gamma-sge", name: "Gamma Sagittae", x: 0.86, y: 0.1, size: 1.4 },
      { id: "delta-sge", name: "Delta Sagittae", x: 0.5, y: 0.4, size: 1.2 },
      { id: "alpha-sge", name: "Alpha Sagittae", x: 0.2, y: 0.6, size: 1.1 },
      { id: "beta-sge", name: "Beta Sagittae", x: 0.06, y: 0.7, size: 1.0 },
    ],
    edges: [
      ["gamma-sge", "delta-sge"],
      ["delta-sge", "alpha-sge"],
      ["alpha-sge", "beta-sge"],
    ],
  },
  {
    id: "equuleus",
    name: "Equuleus",
    fact: "Equuleus is the second-smallest constellation in the entire sky, after Crux — just a tiny knot of faint stars representing a foal's head.",
    stars: [
      { id: "kitalpha", name: "Kitalpha", x: 0.5, y: 0.5, size: 1.4 },
      { id: "delta-equ", name: "Delta Equulei", x: 0.24, y: 0.3, size: 1.1 },
      { id: "gamma-equ", name: "Gamma Equulei", x: 0.7, y: 0.24, size: 1.0 },
    ],
    edges: [
      ["delta-equ", "kitalpha"],
      ["kitalpha", "gamma-equ"],
    ],
  },
  {
    id: "triangulum",
    name: "Triangulum",
    fact: "Small and simple, Triangulum's three stars point the way to the Triangulum Galaxy — one of the most distant objects visible to the naked eye on a clear night.",
    stars: [
      { id: "mothallah", name: "Mothallah", x: 0.16, y: 0.7, size: 1.4 },
      { id: "beta-tri", name: "Beta Trianguli", x: 0.8, y: 0.5, size: 1.5 },
      { id: "gamma-tri", name: "Gamma Trianguli", x: 0.44, y: 0.06, size: 1.2 },
    ],
    edges: [
      ["mothallah", "beta-tri"],
      ["beta-tri", "gamma-tri"],
      ["gamma-tri", "mothallah"],
    ],
  },
  {
    id: "antlia",
    name: "Antlia",
    fact: "Antlia, the Air Pump, is one of the faintest constellations in the sky — invented in the 1750s by Lacaille to honor a piece of laboratory equipment, not a myth.",
    stars: [
      { id: "alpha-ant", name: "Alpha Antliae", x: 0.5, y: 0.3, size: 1.3 },
      { id: "epsilon-ant", name: "Epsilon Antliae", x: 0.2, y: 0.7, size: 1.0 },
      { id: "iota-ant", name: "Iota Antliae", x: 0.8, y: 0.6, size: 1.0 },
    ],
    edges: [
      ["epsilon-ant", "alpha-ant"],
      ["alpha-ant", "iota-ant"],
    ],
  },
  {
    id: "apus",
    name: "Apus",
    fact: "Apus represents a bird of paradise — named by 16th-century Dutch navigators who charted the deep southern sky for the first time.",
    stars: [
      { id: "alpha-aps", name: "Alpha Apodis", x: 0.5, y: 0.2, size: 1.4 },
      { id: "gamma-aps", name: "Gamma Apodis", x: 0.3, y: 0.6, size: 1.1 },
      { id: "beta-aps", name: "Beta Apodis", x: 0.7, y: 0.7, size: 1.1 },
    ],
    edges: [
      ["alpha-aps", "gamma-aps"],
      ["alpha-aps", "beta-aps"],
    ],
  },
  {
    id: "ara",
    name: "Ara",
    fact: "Ara represents an altar — in Greek myth, the one where the gods swore their alliance before the war against the Titans.",
    stars: [
      { id: "beta-ara", name: "Beta Arae", x: 0.5, y: 0.1, size: 1.6 },
      { id: "alpha-ara", name: "Alpha Arae", x: 0.3, y: 0.4, size: 1.4 },
      { id: "zeta-ara", name: "Zeta Arae", x: 0.65, y: 0.5, size: 1.2 },
      { id: "gamma-ara", name: "Gamma Arae", x: 0.45, y: 0.75, size: 1.2 },
    ],
    edges: [
      ["beta-ara", "alpha-ara"],
      ["beta-ara", "zeta-ara"],
      ["zeta-ara", "gamma-ara"],
    ],
  },
  {
    id: "caelum",
    name: "Caelum",
    fact: "Caelum, the Chisel, is the eighth-smallest constellation in the sky — another of Lacaille's 18th-century tributes to tools of the workshop.",
    stars: [
      { id: "alpha-cae", name: "Alpha Caeli", x: 0.4, y: 0.4, size: 1.2 },
      { id: "beta-cae", name: "Beta Caeli", x: 0.7, y: 0.6, size: 1.1 },
    ],
    edges: [["alpha-cae", "beta-cae"]],
  },
  {
    id: "canes-venatici",
    name: "Canes Venatici",
    fact: "Canes Venatici, the Hunting Dogs, holds the Whirlpool Galaxy — one of the first galaxies ever observed to have a clear spiral structure.",
    stars: [
      { id: "cor-caroli", name: "Cor Caroli", x: 0.3, y: 0.3, size: 1.8 },
      { id: "chara", name: "Chara", x: 0.7, y: 0.6, size: 1.2 },
    ],
    edges: [["cor-caroli", "chara"]],
  },
  {
    id: "carina",
    name: "Carina",
    fact: "Carina holds Canopus, the second-brightest star in the entire night sky — and was once part of a much larger constellation, the ship Argo Navis, before being split apart.",
    stars: [
      { id: "canopus", name: "Canopus", x: 0.2, y: 0.5, size: 3.2 },
      { id: "miaplacidus", name: "Miaplacidus", x: 0.5, y: 0.2, size: 2.0 },
      { id: "avior", name: "Avior", x: 0.7, y: 0.7, size: 1.6 },
      { id: "aspidiske", name: "Aspidiske", x: 0.85, y: 0.4, size: 1.4 },
    ],
    edges: [
      ["canopus", "miaplacidus"],
      ["miaplacidus", "aspidiske"],
      ["aspidiske", "avior"],
    ],
  },
  {
    id: "centaurus",
    name: "Centaurus",
    fact: "Centaurus contains Alpha Centauri — the closest star system to our own Sun, just over four light-years away.",
    stars: [
      { id: "rigil-kentaurus", name: "Rigil Kentaurus", x: 0.15, y: 0.6, size: 3.0 },
      { id: "hadar", name: "Hadar", x: 0.35, y: 0.4, size: 2.4 },
      { id: "menkent", name: "Menkent", x: 0.6, y: 0.2, size: 1.6 },
      { id: "epsilon-cen", name: "Epsilon Centauri", x: 0.55, y: 0.65, size: 1.4 },
      { id: "eta-cen", name: "Eta Centauri", x: 0.8, y: 0.5, size: 1.3 },
    ],
    edges: [
      ["rigil-kentaurus", "hadar"],
      ["hadar", "menkent"],
      ["hadar", "epsilon-cen"],
      ["epsilon-cen", "eta-cen"],
    ],
  },
  {
    id: "cetus",
    name: "Cetus",
    fact: "Cetus, the sea monster, is home to Mira — the first-known 'wonder star', a variable star whose brightness swings dramatically over about 11 months.",
    stars: [
      { id: "menkar", name: "Menkar", x: 0.75, y: 0.2, size: 1.9 },
      { id: "diphda", name: "Diphda", x: 0.2, y: 0.7, size: 2.1 },
      { id: "mira", name: "Mira", x: 0.5, y: 0.4, size: 1.5 },
      { id: "eta-cet", name: "Eta Ceti", x: 0.45, y: 0.6, size: 1.2 },
    ],
    edges: [
      ["menkar", "mira"],
      ["mira", "eta-cet"],
      ["eta-cet", "diphda"],
    ],
  },
  {
    id: "chamaeleon",
    name: "Chamaeleon",
    fact: "Chamaeleon is a small, faint southern constellation, named by 16th-century navigators for a creature they'd never seen in a sky they'd never charted before.",
    stars: [
      { id: "alpha-cha", name: "Alpha Chamaeleontis", x: 0.4, y: 0.3, size: 1.3 },
      { id: "beta-cha", name: "Beta Chamaeleontis", x: 0.7, y: 0.6, size: 1.2 },
      { id: "gamma-cha", name: "Gamma Chamaeleontis", x: 0.3, y: 0.7, size: 1.1 },
    ],
    edges: [
      ["alpha-cha", "gamma-cha"],
      ["alpha-cha", "beta-cha"],
    ],
  },
  {
    id: "circinus",
    name: "Circinus",
    fact: "Circinus, the Compass, is a tiny, sharp sliver of a constellation representing a drafting tool — squeezed into the sky right beside Alpha Centauri.",
    stars: [
      { id: "alpha-cir", name: "Alpha Circini", x: 0.5, y: 0.2, size: 1.4 },
      { id: "beta-cir", name: "Beta Circini", x: 0.4, y: 0.6, size: 1.1 },
      { id: "gamma-cir", name: "Gamma Circini", x: 0.65, y: 0.55, size: 1.0 },
    ],
    edges: [
      ["alpha-cir", "beta-cir"],
      ["alpha-cir", "gamma-cir"],
    ],
  },
  {
    id: "coma-berenices",
    name: "Coma Berenices",
    fact: "Coma Berenices is named for a real Egyptian queen's hair, which she cut off as an offering — and it happens to point straight at the Virgo Cluster, thousands of galaxies deep.",
    stars: [
      { id: "diadem", name: "Diadem", x: 0.5, y: 0.3, size: 1.4 },
      { id: "beta-com", name: "Beta Comae Berenices", x: 0.7, y: 0.6, size: 1.3 },
      { id: "gamma-com", name: "Gamma Comae Berenices", x: 0.25, y: 0.55, size: 1.2 },
    ],
    edges: [
      ["gamma-com", "diadem"],
      ["diadem", "beta-com"],
    ],
  },
  {
    id: "corona-australis",
    name: "Corona Australis",
    fact: "Corona Australis, the Southern Crown, mirrors its northern counterpart — a delicate curved arc of stars, this one at the feet of Sagittarius.",
    stars: [
      { id: "alpha-cra", name: "Alpha Coronae Australis", x: 0.3, y: 0.3, size: 1.3 },
      { id: "beta-cra", name: "Beta Coronae Australis", x: 0.5, y: 0.5, size: 1.4 },
      { id: "gamma-cra", name: "Gamma Coronae Australis", x: 0.7, y: 0.4, size: 1.1 },
    ],
    edges: [
      ["alpha-cra", "beta-cra"],
      ["beta-cra", "gamma-cra"],
    ],
  },
  {
    id: "dorado",
    name: "Dorado",
    fact: "Dorado, the swordfish, hosts most of the Large Magellanic Cloud — a small satellite galaxy of the Milky Way, visible to the naked eye only from the far south.",
    stars: [
      { id: "alpha-dor", name: "Alpha Doradus", x: 0.5, y: 0.2, size: 1.6 },
      { id: "beta-dor", name: "Beta Doradus", x: 0.35, y: 0.55, size: 1.4 },
      { id: "gamma-dor", name: "Gamma Doradus", x: 0.65, y: 0.6, size: 1.1 },
    ],
    edges: [
      ["alpha-dor", "beta-dor"],
      ["alpha-dor", "gamma-dor"],
    ],
  },
  {
    id: "eridanus",
    name: "Eridanus",
    fact: "Eridanus, the River, is the sixth-largest constellation and one of the longest, winding from near Orion all the way down to Achernar, deep in the southern sky.",
    stars: [
      { id: "achernar", name: "Achernar", x: 0.1, y: 0.9, size: 2.6 },
      { id: "cursa", name: "Cursa", x: 0.85, y: 0.05, size: 1.6 },
      { id: "acamar", name: "Acamar", x: 0.3, y: 0.7, size: 1.5 },
      { id: "zaurak", name: "Zaurak", x: 0.6, y: 0.35, size: 1.3 },
    ],
    edges: [
      ["cursa", "zaurak"],
      ["zaurak", "acamar"],
      ["acamar", "achernar"],
    ],
  },
  {
    id: "fornax",
    name: "Fornax",
    fact: "Fornax, the Furnace, is faint and mostly empty to the eye — but deep telescope images of this patch of sky revealed thousands of distant galaxies behind it.",
    stars: [
      { id: "alpha-for", name: "Alpha Fornacis", x: 0.4, y: 0.4, size: 1.4 },
      { id: "beta-for", name: "Beta Fornacis", x: 0.7, y: 0.6, size: 1.1 },
    ],
    edges: [["alpha-for", "beta-for"]],
  },
  {
    id: "grus",
    name: "Grus",
    fact: "Grus, the Crane, is one of several southern 'bird' constellations charted together by Dutch navigators at the end of the 16th century.",
    stars: [
      { id: "alnair", name: "Alnair", x: 0.3, y: 0.3, size: 1.9 },
      { id: "beta-gru", name: "Beta Gruis", x: 0.6, y: 0.5, size: 1.7 },
      { id: "gamma-gru", name: "Gamma Gruis", x: 0.4, y: 0.75, size: 1.3 },
      { id: "delta-gru", name: "Delta Gruis", x: 0.75, y: 0.3, size: 1.2 },
    ],
    edges: [
      ["alnair", "beta-gru"],
      ["beta-gru", "gamma-gru"],
      ["beta-gru", "delta-gru"],
    ],
  },
  {
    id: "horologium",
    name: "Horologium",
    fact: "Horologium, the Clock, is a dim tribute to the pendulum clock — invented by Lacaille alongside a whole workshop's worth of southern constellations.",
    stars: [
      { id: "alpha-hor", name: "Alpha Horologii", x: 0.5, y: 0.3, size: 1.3 },
      { id: "delta-hor", name: "Delta Horologii", x: 0.3, y: 0.6, size: 1.0 },
    ],
    edges: [["alpha-hor", "delta-hor"]],
  },
  {
    id: "hydrus",
    name: "Hydrus",
    fact: "Hydrus, the Little Water Snake, is a small southern constellation that winds between the two Magellanic Clouds without touching either.",
    stars: [
      { id: "alpha-hyi", name: "Alpha Hydri", x: 0.6, y: 0.75, size: 1.6 },
      { id: "beta-hyi", name: "Beta Hydri", x: 0.3, y: 0.85, size: 1.5 },
      { id: "gamma-hyi", name: "Gamma Hydri", x: 0.4, y: 0.2, size: 1.3 },
    ],
    edges: [
      ["gamma-hyi", "alpha-hyi"],
      ["alpha-hyi", "beta-hyi"],
    ],
  },
  {
    id: "indus",
    name: "Indus",
    fact: "Indus, the Indian, was named by 16th-century Dutch navigators for the peoples they encountered on their voyages — one of several human figures added to the southern sky.",
    stars: [
      { id: "alpha-ind", name: "Alpha Indi", x: 0.4, y: 0.3, size: 1.5 },
      { id: "beta-ind", name: "Beta Indi", x: 0.65, y: 0.55, size: 1.3 },
      { id: "delta-ind", name: "Delta Indi", x: 0.3, y: 0.7, size: 1.1 },
    ],
    edges: [
      ["alpha-ind", "beta-ind"],
      ["beta-ind", "delta-ind"],
    ],
  },
  {
    id: "lacerta",
    name: "Lacerta",
    fact: "Lacerta, the Lizard, is a small zigzag of faint stars wedged between Cygnus and Andromeda — invented in the 1600s simply to fill the gap.",
    stars: [
      { id: "alpha-lac", name: "Alpha Lacertae", x: 0.5, y: 0.2, size: 1.3 },
      { id: "beta-lac", name: "Beta Lacertae", x: 0.3, y: 0.5, size: 1.0 },
      { id: "4-lac", name: "4 Lacertae", x: 0.7, y: 0.6, size: 1.0 },
    ],
    edges: [
      ["alpha-lac", "beta-lac"],
      ["alpha-lac", "4-lac"],
    ],
  },
  {
    id: "leo-minor",
    name: "Leo Minor",
    fact: "Leo Minor, the Smaller Lion, has no star even bright enough to have earned a Bayer letter designation until astronomers finally assigned one in the 1840s.",
    stars: [
      { id: "46-lmi", name: "46 Leonis Minoris", x: 0.5, y: 0.4, size: 1.3 },
      { id: "beta-lmi", name: "Beta Leonis Minoris", x: 0.3, y: 0.6, size: 1.1 },
    ],
    edges: [["46-lmi", "beta-lmi"]],
  },
  {
    id: "lupus",
    name: "Lupus",
    fact: "Lupus, the Wolf, was recorded by ancient Babylonian astronomers as a wild animal held on a pole by neighboring Centaurus, ready for sacrifice.",
    stars: [
      { id: "alpha-lup", name: "Alpha Lupi", x: 0.5, y: 0.2, size: 1.8 },
      { id: "beta-lup", name: "Beta Lupi", x: 0.3, y: 0.5, size: 1.6 },
      { id: "gamma-lup", name: "Gamma Lupi", x: 0.65, y: 0.55, size: 1.4 },
      { id: "delta-lup", name: "Delta Lupi", x: 0.45, y: 0.75, size: 1.2 },
    ],
    edges: [
      ["alpha-lup", "beta-lup"],
      ["alpha-lup", "gamma-lup"],
      ["beta-lup", "delta-lup"],
    ],
  },
  {
    id: "mensa",
    name: "Mensa",
    fact: "Mensa is the only constellation named after a real place on Earth — South Africa's Table Mountain — and it's the faintest constellation in the entire sky.",
    stars: [
      { id: "alpha-men", name: "Alpha Mensae", x: 0.5, y: 0.5, size: 1.1 },
      { id: "beta-men", name: "Beta Mensae", x: 0.75, y: 0.3, size: 0.9 },
    ],
    edges: [["alpha-men", "beta-men"]],
  },
  {
    id: "microscopium",
    name: "Microscopium",
    fact: "Microscopium is another of Lacaille's scientific-instrument constellations — so faint that ancient astronomers never had reason to name this patch of sky at all.",
    stars: [
      { id: "gamma-mic", name: "Gamma Microscopii", x: 0.5, y: 0.3, size: 1.2 },
      { id: "alpha-mic", name: "Alpha Microscopii", x: 0.3, y: 0.6, size: 1.0 },
    ],
    edges: [["gamma-mic", "alpha-mic"]],
  },
  {
    id: "musca",
    name: "Musca",
    fact: "Musca, the Fly, is the only insect among the 88 constellations — a small, distinct diamond of stars just south of the Southern Cross.",
    stars: [
      { id: "alpha-mus", name: "Alpha Muscae", x: 0.5, y: 0.8, size: 1.6 },
      { id: "beta-mus", name: "Beta Muscae", x: 0.4, y: 0.5, size: 1.4 },
      { id: "gamma-mus", name: "Gamma Muscae", x: 0.6, y: 0.3, size: 1.2 },
      { id: "delta-mus", name: "Delta Muscae", x: 0.7, y: 0.55, size: 1.1 },
    ],
    edges: [
      ["gamma-mus", "beta-mus"],
      ["beta-mus", "alpha-mus"],
      ["beta-mus", "delta-mus"],
    ],
  },
  {
    id: "norma",
    name: "Norma",
    fact: "Norma, the Carpenter's Square, lost its brightest stars to neighboring constellations during 19th-century boundary redraws — it no longer even has an Alpha or Beta star.",
    stars: [
      { id: "gamma2-nor", name: "Gamma-2 Normae", x: 0.5, y: 0.3, size: 1.2 },
      { id: "epsilon-nor", name: "Epsilon Normae", x: 0.3, y: 0.6, size: 1.0 },
      { id: "iota1-nor", name: "Iota-1 Normae", x: 0.65, y: 0.55, size: 1.0 },
    ],
    edges: [
      ["gamma2-nor", "epsilon-nor"],
      ["gamma2-nor", "iota1-nor"],
    ],
  },
  {
    id: "octans",
    name: "Octans",
    fact: "Octans contains the south celestial pole — but unlike Polaris in the north, its pole star, Sigma Octantis, is so faint it's barely useful for navigation.",
    stars: [
      { id: "sigma-oct", name: "Sigma Octantis", x: 0.5, y: 0.5, size: 1.0 },
      { id: "nu-oct", name: "Nu Octantis", x: 0.3, y: 0.3, size: 1.3 },
      { id: "beta-oct", name: "Beta Octantis", x: 0.7, y: 0.35, size: 1.1 },
    ],
    edges: [
      ["nu-oct", "sigma-oct"],
      ["sigma-oct", "beta-oct"],
    ],
  },
  {
    id: "pavo",
    name: "Pavo",
    fact: "Pavo, the Peacock, lent its brightest star's name — Peacock — to one of the 57 stars selected for celestial navigation by 20th-century aviators.",
    stars: [
      { id: "peacock", name: "Peacock", x: 0.3, y: 0.3, size: 1.9 },
      { id: "beta-pav", name: "Beta Pavonis", x: 0.55, y: 0.5, size: 1.4 },
      { id: "delta-pav", name: "Delta Pavonis", x: 0.4, y: 0.7, size: 1.2 },
    ],
    edges: [
      ["peacock", "beta-pav"],
      ["beta-pav", "delta-pav"],
    ],
  },
  {
    id: "phoenix",
    name: "Phoenix",
    fact: "Phoenix represents the mythical bird reborn from its own ashes — a fitting name for a constellation charted fresh into a part of the sky no one had mapped before.",
    stars: [
      { id: "ankaa", name: "Ankaa", x: 0.5, y: 0.4, size: 1.8 },
      { id: "beta-phe", name: "Beta Phoenicis", x: 0.3, y: 0.6, size: 1.4 },
      { id: "gamma-phe", name: "Gamma Phoenicis", x: 0.7, y: 0.55, size: 1.2 },
    ],
    edges: [
      ["ankaa", "beta-phe"],
      ["ankaa", "gamma-phe"],
    ],
  },
  {
    id: "pictor",
    name: "Pictor",
    fact: "Pictor's second star, Beta Pictoris, is famous among astronomers for its visible disk of dust and gas — one of the first planetary systems ever imaged in the middle of forming.",
    stars: [
      { id: "alpha-pic", name: "Alpha Pictoris", x: 0.5, y: 0.3, size: 1.4 },
      { id: "beta-pic", name: "Beta Pictoris", x: 0.3, y: 0.65, size: 1.5 },
    ],
    edges: [["alpha-pic", "beta-pic"]],
  },
  {
    id: "piscis-austrinus",
    name: "Piscis Austrinus",
    fact: "Piscis Austrinus, the Southern Fish, holds Fomalhaut — one of the closest bright stars to Earth, and one of the first ever found with a directly photographed planet.",
    stars: [
      { id: "fomalhaut", name: "Fomalhaut", x: 0.4, y: 0.6, size: 2.4 },
      { id: "epsilon-psa", name: "Epsilon Piscis Austrini", x: 0.6, y: 0.3, size: 1.2 },
      { id: "mu-psa", name: "Mu Piscis Austrini", x: 0.25, y: 0.35, size: 1.1 },
    ],
    edges: [
      ["mu-psa", "epsilon-psa"],
      ["epsilon-psa", "fomalhaut"],
    ],
  },
  {
    id: "puppis",
    name: "Puppis",
    fact: "Puppis, the Poop Deck, is another remnant of the once-huge ship Argo Navis — split apart in the 1750s because the original was simply too large to be practical.",
    stars: [
      { id: "naos", name: "Naos", x: 0.5, y: 0.4, size: 1.8 },
      { id: "rho-pup", name: "Rho Puppis", x: 0.7, y: 0.2, size: 1.4 },
      { id: "tau-pup", name: "Tau Puppis", x: 0.3, y: 0.65, size: 1.3 },
    ],
    edges: [
      ["rho-pup", "naos"],
      ["naos", "tau-pup"],
    ],
  },
  {
    id: "pyxis",
    name: "Pyxis",
    fact: "Pyxis, the Compass Box, represents the ship's navigational compass — a strange addition, since the rest of the original ship Argo Navis predates the compass by millennia.",
    stars: [
      { id: "alpha-pyx", name: "Alpha Pyxidis", x: 0.5, y: 0.3, size: 1.3 },
      { id: "beta-pyx", name: "Beta Pyxidis", x: 0.45, y: 0.6, size: 1.0 },
    ],
    edges: [["alpha-pyx", "beta-pyx"]],
  },
  {
    id: "reticulum",
    name: "Reticulum",
    fact: "Reticulum is named for the crosshair reticle in a telescope eyepiece — a tool astronomers used to measure star positions precisely, memorialized in the sky itself.",
    stars: [
      { id: "alpha-ret", name: "Alpha Reticuli", x: 0.5, y: 0.6, size: 1.3 },
      { id: "beta-ret", name: "Beta Reticuli", x: 0.35, y: 0.35, size: 1.2 },
    ],
    edges: [["beta-ret", "alpha-ret"]],
  },
  {
    id: "sculptor",
    name: "Sculptor",
    fact: "Sculptor lies near the south galactic pole, giving an unusually clear view straight out of the Milky Way's dusty disk toward other galaxies — including the nearby Sculptor Galaxy.",
    stars: [
      { id: "alpha-scl", name: "Alpha Sculptoris", x: 0.5, y: 0.3, size: 1.3 },
      { id: "beta-scl", name: "Beta Sculptoris", x: 0.3, y: 0.6, size: 1.1 },
    ],
    edges: [["alpha-scl", "beta-scl"]],
  },
  {
    id: "scutum",
    name: "Scutum",
    fact: "Scutum, the Shield, is small and faint, but it sits in a rich part of the Milky Way — home to the Wild Duck Cluster, one of the densest open star clusters known.",
    stars: [
      { id: "alpha-sct", name: "Alpha Scuti", x: 0.5, y: 0.3, size: 1.3 },
      { id: "beta-sct", name: "Beta Scuti", x: 0.3, y: 0.6, size: 1.1 },
      { id: "delta-sct", name: "Delta Scuti", x: 0.7, y: 0.55, size: 1.0 },
    ],
    edges: [
      ["alpha-sct", "beta-sct"],
      ["alpha-sct", "delta-sct"],
    ],
  },
  {
    id: "serpens",
    name: "Serpens",
    fact: "Serpens is the only constellation split into two separate pieces — Caput (the head) and Cauda (the tail) — divided by Ophiuchus, the serpent-bearer holding it.",
    stars: [
      { id: "unukalhai", name: "Unukalhai", x: 0.2, y: 0.4, size: 1.6 },
      { id: "beta-ser", name: "Beta Serpentis", x: 0.35, y: 0.2, size: 1.2 },
      { id: "eta-ser", name: "Eta Serpentis", x: 0.7, y: 0.65, size: 1.3 },
      { id: "theta-ser", name: "Theta Serpentis", x: 0.9, y: 0.5, size: 1.1 },
    ],
    edges: [
      ["beta-ser", "unukalhai"],
      ["unukalhai", "eta-ser"],
      ["eta-ser", "theta-ser"],
    ],
  },
  {
    id: "telescopium",
    name: "Telescopium",
    fact: "Telescopium honors the instrument that made every other constellation's faint stars visible in the first place — though its own stars are dim enough to need one.",
    stars: [
      { id: "alpha-tel", name: "Alpha Telescopii", x: 0.5, y: 0.3, size: 1.3 },
      { id: "zeta-tel", name: "Zeta Telescopii", x: 0.3, y: 0.6, size: 1.0 },
    ],
    edges: [["alpha-tel", "zeta-tel"]],
  },
  {
    id: "triangulum-australe",
    name: "Triangulum Australe",
    fact: "Triangulum Australe, the Southern Triangle, is small but unmistakable — a nearly perfect, bright triangle of stars that early southern navigators used for orientation.",
    stars: [
      { id: "atria", name: "Atria", x: 0.5, y: 0.2, size: 1.8 },
      { id: "beta-tra", name: "Beta Trianguli Australis", x: 0.25, y: 0.7, size: 1.4 },
      { id: "gamma-tra", name: "Gamma Trianguli Australis", x: 0.75, y: 0.65, size: 1.3 },
    ],
    edges: [
      ["atria", "beta-tra"],
      ["atria", "gamma-tra"],
      ["beta-tra", "gamma-tra"],
    ],
  },
  {
    id: "tucana",
    name: "Tucana",
    fact: "Tucana, the Toucan, hosts the Small Magellanic Cloud and 47 Tucanae — one of the brightest globular star clusters in the entire sky.",
    stars: [
      { id: "alpha-tuc", name: "Alpha Tucanae", x: 0.5, y: 0.3, size: 1.6 },
      { id: "gamma-tuc", name: "Gamma Tucanae", x: 0.3, y: 0.55, size: 1.2 },
      { id: "zeta-tuc", name: "Zeta Tucanae", x: 0.7, y: 0.6, size: 1.2 },
    ],
    edges: [
      ["alpha-tuc", "gamma-tuc"],
      ["alpha-tuc", "zeta-tuc"],
    ],
  },
  {
    id: "vela",
    name: "Vela",
    fact: "Vela, the Sails, is the third piece of the dismembered ship Argo Navis — its stars, together with Carina's, form the 'False Cross', often mistaken for the true Southern Cross.",
    stars: [
      { id: "regor", name: "Regor", x: 0.3, y: 0.3, size: 2.0 },
      { id: "delta-vel", name: "Delta Velorum", x: 0.55, y: 0.5, size: 1.6 },
      { id: "kappa-vel", name: "Kappa Velorum", x: 0.4, y: 0.65, size: 1.4 },
      { id: "lambda-vel", name: "Lambda Velorum", x: 0.75, y: 0.35, size: 1.5 },
    ],
    edges: [
      ["regor", "delta-vel"],
      ["delta-vel", "kappa-vel"],
      ["delta-vel", "lambda-vel"],
    ],
  },
  {
    id: "volans",
    name: "Volans",
    fact: "Volans, the Flying Fish, commemorates a real fish that leaps from the ocean to glide above the waves — spotted often by the same 16th-century sailors who named this sky.",
    stars: [
      { id: "beta-vol", name: "Beta Volantis", x: 0.5, y: 0.4, size: 1.4 },
      { id: "alpha-vol", name: "Alpha Volantis", x: 0.3, y: 0.65, size: 1.2 },
      { id: "gamma-vol", name: "Gamma Volantis", x: 0.7, y: 0.6, size: 1.1 },
    ],
    edges: [
      ["alpha-vol", "beta-vol"],
      ["beta-vol", "gamma-vol"],
    ],
  },
  {
    id: "vulpecula",
    name: "Vulpecula",
    fact: "Vulpecula, the Fox, holds the Dumbbell Nebula and marks the spot where the very first pulsar was ever discovered, in 1967 — a spinning neutron star flashing with clockwork precision.",
    stars: [
      { id: "anser", name: "Anser", x: 0.5, y: 0.4, size: 1.4 },
      { id: "23-vul", name: "23 Vulpeculae", x: 0.3, y: 0.65, size: 1.0 },
    ],
    edges: [["anser", "23-vul"]],
  },
];
